### ISSUE TITLE
issues about running test.py

### ISSUE THREAD

**Issue by doug919** [Cadene/skip-thoughts.torch#3]
I was trying to run your [skip-thoughts.torch/pytorch/test.py](https://github.com/Cadene/skip-thoughts.torch/blob/master/pytorch/test.py). However, I couldn't find the test files that should locate in the folder "../data/test". Is there a way that I can get these files?

https://github.com/Cadene/skip-thoughts.torch/blob/9cc23adaa4a08828a55a1a73671c6f15054c1b0e/pytorch/test.py#L165

**Comment by Cadene** [comment]
Those files are created using python [dump_features.py](https://github.com/Cadene/skip-thoughts.torch/blob/master/theano/dump_features.py):
https://github.com/Cadene/skip-thoughts.torch/blob/9cc23adaa4a08828a55a1a73671c6f15054c1b0e/pytorch/test.py#L169

dump_features load the parameters (https://github.com/Cadene/skip-thoughts/tree/2a63a245562771adbe8a4a08a73f529aa3dd1d10#getting-started) using the theano code.

If you need more info, let me know

**Comment by doug919** [comment]
I see. I missed that. Thanks for the clarification. It's a good implementation and I might use it in my project.
